-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- Default shell
vim.opt.shell = "fish"

-- Dynamic change border color based on Neovim mode
vim.opt.title = true
vim.api.nvim_create_autocmd({ "ModeChanged", "VimEnter", "BufEnter" }, {
  callback = function()
    local mode = string.upper(vim.fn.mode())
    local filename = vim.fn.expand("%:t")

    if filename == "" then
      vim.opt.titlestring = "nvim-" .. mode .. " [Scratch]"
      return
    end

    vim.opt.titlestring = "nvim-" .. mode .. " - %t"
  end,
})

-- NOTE: Generate theme again by uncomment below

-- local function generate_niri_rules()
--   local function get_hl_hex(hl_name, attr, fallback)
--     local hl = vim.api.nvim_get_hl(0, { name = hl_name, link = false })
--     if hl and hl[attr] then
--       return string.format("#%06x", hl[attr])
--     end
--     return fallback
--   end
--
--   local normal_color = get_hl_hex("Function", "fg", "#89b4fa")
--   local insert_color = get_hl_hex("String", "fg", "#a6e3a1")
--   local visual_color = get_hl_hex("Keyword", "fg", "#cba6f7")
--   local command_color = "#fab388"
--   local inactive_color = get_hl_hex("Normal", "bg", "#1e1e2e")
--   local urgent_color = get_hl_hex("Error", "fg", "#f38ba8")
--
--   local kdl_content = string.format(
--     [[
-- // Auto-generated by Neovim. Do not edit manually.
--
-- window-rule {
--     match title="^nvim-N"
--     border {
--         active-color   "%s"
--         inactive-color "%s"
--         urgent-color   "%s"
--     }
-- }
--
-- window-rule {
--     match title="^nvim-I"
--     border {
--         active-color   "%s"
--         inactive-color "%s"
--         urgent-color   "%s"
--     }
-- }
--
-- window-rule {
--     match title="^nvim-V"
--     border {
--         active-color   "%s"
--         inactive-color "%s"
--         urgent-color   "%s"
--     }
-- }
--
-- window-rule {
--     match title="^nvim-C"
--     border {
--         active-color   "%s"
--         inactive-color "%s"
--         urgent-color   "%s"
--     }
-- }
-- ]],
--     normal_color,
--     inactive_color,
--     urgent_color,
--     insert_color,
--     inactive_color,
--     urgent_color,
--     visual_color,
--     inactive_color,
--     urgent_color,
--     command_color,
--     inactive_color,
--     urgent_color
--   )
--
--   local filepath = vim.fn.expand("~/.config/niri/modules/nvim-modes.kdl")
--   local file = io.open(filepath, "w")
--   if file then
--     file:write(kdl_content)
--     file:close()
--   end
-- end
--
-- vim.api.nvim_create_autocmd({ "VimEnter", "ColorScheme" }, {
--   callback = generate_niri_rules,
-- })
